spring:
  application:
    name: discovery-service
  security:
    user:
      name: admin
      password: admin123
      
    
eureka:
  instance:
    hostname: localhost
  client:
      register-with-eureka: false  # equivalent to exclude spring-cloud-netflix-eureka-client in pom    
      fetch-registry: false

server:
  port: 8761